Ft user password reset 165742482
henperi/safescrow-bend pull request #14
Opened 2020-02-12 15:35 UTC by sudhons

# Description

`Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.`

# Issue ID/Link

`Choose one below and replace with the relevant Issue ID or Link. Delete the unused option`

- [ ] Pivotal Tracker [#Issue Id](https://www.pivotaltracker.com/story/show/<IssueId>)
- [ ] Jira [#Issue Id](https://www.jira.com/story/show/<IssueId>)

# What kinds of changes does this PR introduce?

`Please delete options that are not relevant.`

- [ ] Non-breaking **_[Bug Fix]_** which fixes an issue/bug.
- [ ] Non-breaking **_[Feature]_** which adds functionality.
- [ ] Non-breaking **_[Chore]_** which adds functionality.
- [ ] Breaking change **_[Fix|Feature|Chore]_** that would/may cause existing functionality not to work as expected.
- [ ] This change requires a documentation update.

# How Has This Been Manually Tested?

`Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce and/or test it accordingly.`

- Scenaria for Test A
- Scenario for Test B etc...

# Test Coverage:

`Add test coverage details for before and after.`

- Current Coverage: []%
- New Coverage if merged: []%

# Checklist:

`Ensure you are able to check all the listed options below. If not fill the additional context in the section below.`

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Additional Context

`Optional section, can be used to give insights, or just lodge complaints regarding this PR.`

2020-02-14 10:25 UTC, henperi requested changes

2020-02-14 10:25 UTC, henperi commented on src/controllers/AuthController.ts
> +      res.locals = { ...res.locals, dbUser: user };
Can we just have our user in `res.locals.user `as opposed to `res.locals.dbUser`?

2020-02-14 10:25 UTC, henperi commented on src/controllers/AuthController.ts
> +        res.locals.dbUser,
consider `res.locals.user` as opposed to `req.locals.dbUser`

2020-02-14 10:25 UTC, henperi commented on src/helpers/tokenHelpers.ts
> +      expiresIn: '1d',
I think we should go for 3 hours or less here.

2020-02-14 10:25 UTC, henperi commented on src/routes/auth/index.ts
> +  '/reset-password',
Also, consider changing the endpoint name to something that relates to sending the reset email.

2020-02-14 10:25 UTC, henperi commented on src/controllers/AuthController.ts
> +  static async resetPassword(req: Express.Request, res: Express.Response): Promise<void> {
Great implementation here bro, but I'm looking at the name of this method(resetPassword) and the description(Method to reset a User's password) above it. I think we should modify its name/description.
*Why?* `Because this method doesn't really reset the password. It just sends an email that helps you reset the password.`

I think the name should be related to sending reset email or something in that line. Perhaps `sendResetPasswordEmail`, or `resetPasswordRequest` might suffice.

I'd like to know your thoughts on my perspective.

2020-02-19 11:22 UTC, henperi requested changes

2020-02-19 11:22 UTC, henperi commented on package.json
> +    "@types/sinon": "^7.5.1",
This should be in dev dependecy

2020-02-19 11:22 UTC, henperi commented on src/controllers/AuthController.ts
> +  static async checkUser(
This middleware method should be in the middleware folder

2020-02-19 11:22 UTC, henperi commented on tests/unitTests/controllers/AuthController.spec.ts
> +      await AuthController.handlePasswordRestRequest(request, response);
The name `handlePasswordRestRequest` should be modified to `handlePasswordResetRequest`

2020-02-19 11:22 UTC, henperi commented on src/controllers/AuthController.ts
> +const passwordRestCallbackURL = process.env.PASSWORD_RESET_CALLBACK_URL;
I noticed dotenv is not imported in this file. Are we still able to access environment variables like this?

2020-02-19 11:22 UTC, henperi commented on src/controllers/AuthController.ts
> +  static async handlePasswordRestRequest(
Theres a typo on this method's name. I think you meant to write `handlePasswordResetRequest `

2020-02-19 11:22 UTC, henperi commented
Kindly rebase as well

2020-02-19 13:44 UTC, sudhons commented on src/controllers/AuthController.ts
> +const passwordRestCallbackURL = process.env.PASSWORD_RESET_CALLBACK_URL;
You don't need `dotenv` to access environment variables from `process.env`. You only need it to load the variables from `.env` file into `process.env` and you can always access it from there.
You import `dontenv` once in your application that's why it's important to do this early in your application before any file needs any environment variable.

2020-02-19 14:30 UTC, henperi approved these changes

2020-02-19 14:30 UTC, merged